"""
report_builder.py
PR コメント用の AI 修正レポートを構築する。
"""

from datetime import datetime, timedelta, timezone

JST = timezone(timedelta(hours=9))


def build_fix_report(
    pr_number: int,
    attempt: int,
    max_attempts: int,
    reviews: list,
    files_changed: list,
    commit_hash: str,
    committed: bool,
) -> str:
    """AI修正レポートのMarkdown文字列を返す。"""
    timestamp = datetime.now(JST).strftime("%Y-%m-%dT%H:%M:%S+09:00 (JST)")
    short_hash = commit_hash[:7] if commit_hash else "N/A"

    lines = [
        "## AI Auto Fix Report",
        "",
        f"**Fix attempt:** {attempt}/{max_attempts}",
        f"**Timestamp:** {timestamp}",
    ]

    if committed:
        lines.append(f"**Commit:** `{short_hash}`")
    else:
        lines.append("**Commit:** No changes committed")

    lines += ["", "### Reviews Addressed", ""]
    for r in reviews:
        lines.append(f"- Review by **{r.user_login}** `{r.state}` (id: `{r.id}`)")
        if r.body:
            preview = r.body[:120].replace("\n", " ")
            if len(r.body) > 120:
                preview += "..."
            lines.append(f"  > {preview}")

    if files_changed:
        lines += ["", "### Changed Files", ""]
        for f in files_changed:
            lines.append(f"- `{f}`")
    elif committed:
        lines += ["", "### Changed Files", "", "_(no files listed)_"]

    lines += [
        "",
        "---",
        "*Generated by [auto-review-fix-vc](https://github.com/aloekun/auto-review-fix-vc) daemon*",
    ]

    return "\n".join(lines)
